name: Compare to PTDS-DDSS

on:
  workflow_dispatch:
    inputs:
      extra-arguments:
        default: ""
        required: false
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    name: Compile source files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: View system info
        run: lscpu

      - name: Setup Rust
        run: curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf | sh -s -- --default-toolchain=1.89 -y

      - name: Compile source files
        run: cargo build --release

      - name: Display help menu
        run: target/release/min-timespan-delivery run --help

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: executable
          path: target/release/min-timespan-delivery

  solve-ptds-ddss:
    name: Solve PTDS-DDSS
    runs-on: ubuntu-latest
    needs: build
    strategy:
      fail-fast: false
      matrix:
        steps: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Download executable
        uses: actions/download-artifact@v4
        with:
          name: executable
          path: .

      - name: Update permission
        run: chmod +x min-timespan-delivery

      - name: Run algorithm
        run: |
          exitcode=0
          set +e
          let begin=${{ matrix.steps }}+1
          let end=$begin+0

          execute() {
            command=$1
            echo "Running \"$command\""
            $command

            status=$?
            if [ $status -ne 0 ]; then
              echo "::error::\"$command\" exit with status $status"
              exitcode=1
            fi
          }

          for path in $(find problems/ptds-ddss/*)
          do
            arguments=$(python scripts/ptds-ddss.py $path)
            for i in $(seq $begin $end)
            do
              echo "RUN #$i"
              execute "./min-timespan-delivery $arguments ${{ inputs.extra-arguments }} --single-truck-route --disable-logging --extra ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            done
          done

          exit $exitcode

      - name: Upload results
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: output-${{ matrix.steps }}
          path: outputs/*

  compare:
    name: Compare algorithms
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: solve-ptds-ddss

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Download results
        uses: actions/download-artifact@v4
        with:
          path: outputs/
          pattern: output-*
          merge-multiple: true

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Summarize results
        run: python scripts/ptds-ddss-compare.py

      - name: Upload summary files
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: summary-csv
          path: |
            outputs/summary.csv
            outputs/summary.db

      - name: Upload all output files
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: summary
          path: outputs/*
